---
title: Analysis
description:
toc: true
featuredVideo:
featuredImage: /images/nba_analysis.png
draft: false
---


<div id="TOC">

</div>

<div id="motivation-and-initial-questions" class="section level2">
<h2>Motivation and Initial Questions</h2>
<p>For the EDA, our initial questions are
What are the variables that have the most significant contribution to a team’s competence?
Are these variables we interested in truly increasing the chance of a team winning the championship?
Can we make championship predictions based on the variables we selected?
What type of model can we use to make the predictions, is the model reliable/accurate?
What are some limitations of the model and other factors that have potential influence on our prediction?</p>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<p>In this model section, our goal is trying to predict the chance of each NBA team winning the 2017 championship based on variables we believe have the most significant contribution to a team’s competence. To be able to making the most reliable model and prediction, we decide to use the most recent 3 year’s data from every team for our analysis, which takes many considerations into the account, including changes in player’s style, intensity of defense, rules of calls and other factors that made big difference between now day’s NBA and earlier time. In order to find out the strongest predictor variables, we used the AIC method to investigate the significance of every variable of our interest. After the predictor variables have been determined, we then make the logistic regression that has predictor variables and the response variables which is 1 and 0 indicating whether the team we are interested in made into playoffs each year. Below are the steps for the model selection.</p>
<pre><code>## 
## Call:  glm(formula = playoff ~ mean_age + mean_stl + mean_ast + mean_blk + 
##     mean_3p, family = &quot;binomial&quot;, data = combine4)
## 
## Coefficients:
## (Intercept)     mean_age     mean_stl     mean_ast     mean_blk      mean_3p  
##    -6.00907      0.22325     -0.07496      0.01245      0.07793     -1.02168  
## 
## Degrees of Freedom: 30 Total (i.e. Null);  25 Residual
## Null Deviance:       42.94 
## Residual Deviance: 41.63     AIC: 53.63</code></pre>
<pre><code>## 
## Call:
## glm(formula = playoff ~ mean_age + mean_stl + mean_ast + mean_blk + 
##     mean_3p, family = &quot;binomial&quot;, data = combine4)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.535  -1.170   0.855   1.076   1.541  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -6.00907    7.14359  -0.841    0.400
## mean_age     0.22325    0.27041   0.826    0.409
## mean_stl    -0.07496    0.12108  -0.619    0.536
## mean_ast     0.01245    0.04443   0.280    0.779
## mean_blk     0.07793    0.09718   0.802    0.423
## mean_3p     -1.02168    9.40927  -0.109    0.914
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 42.943  on 30  degrees of freedom
## Residual deviance: 41.635  on 25  degrees of freedom
## AIC: 53.635
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-2-1.png" width="672" />
For 2014, our AIC model has given us the best predictors with the lowest AIC value of 53.63. these variables are: Player’s age, steal, assist,block and three points. however, for our logistic regression, these predictors has no significant contribution to our desire model, so 2014 data may not be our best candidates for our prediction model.
The ROC-AUC Curve tells how good our model is and based on the AUC value( 0.625), we believe that our model has moderate accuracy for the prediction.</p>
<p><br></p>
<pre><code>## 
## Call:
## glm(formula = playoff ~ mean_age + mean_stl + mean_ast + mean_blk, 
##     family = &quot;binomial&quot;, data = combine5)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.635  -1.072   0.355   1.034   1.710  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -3.97059    7.75200  -0.512   0.6085  
## mean_age     0.15855    0.29763   0.533   0.5942  
## mean_stl    -0.19647    0.11485  -1.711   0.0871 .
## mean_ast     0.09010    0.05253   1.715   0.0863 .
## mean_blk    -0.10906    0.11812  -0.923   0.3558  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 42.943  on 30  degrees of freedom
## Residual deviance: 37.890  on 26  degrees of freedom
## AIC: 47.89
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-3-1.png" width="672" />
With 2015’s data, we got the best predictor variables(age, steal, assist, block) from AIC method and this time the AIC drops to 47.89. our logistic regression showed that assist and steal are significant predictors variable but the rest of predictors are still remain insignificant. The ROC-AUC Curve is better than 2014’s model with the AUC value of 0.717. So we believe that this model also has moderate accuracy for the prediction and is a better choice than 2014’s prediction model.</p>
<p><br></p>
<pre><code>## Start:  AIC=36.38
## playoff ~ mean_per + mean_trb + mean_ast + mean_blk + mean_3p + 
##     mean_age + mean_G + mean_stl + mean_tov + mean_ows + mean_vorp + 
##     mean_ws + mean_pf + mean_fg + mean_ts
## 
##             Df Deviance    AIC
## - mean_ows   1   1.9611 34.399
## - mean_G     1   1.9611 34.400
## - mean_ws    1   1.9645 34.453
## - mean_trb   1   1.9657 34.472
## - mean_ts    1   1.9726 34.580
## - mean_fg    1   1.9850 34.774
## - mean_tov   1   1.9937 34.910
## - mean_vorp  1   1.9942 34.918
## - mean_ast   1   2.0228 35.360
## - mean_per   1   2.0460 35.713
## - mean_stl   1   2.0745 36.143
## &lt;none&gt;           1.9602 36.384
## - mean_pf    1   2.0933 36.421
## - mean_age   1   2.1226 36.852
## - mean_3p    1   2.2224 38.277
## - mean_blk   1   2.2348 38.449
## 
## Step:  AIC=34.4
## playoff ~ mean_per + mean_trb + mean_ast + mean_blk + mean_3p + 
##     mean_age + mean_G + mean_stl + mean_tov + mean_vorp + mean_ws + 
##     mean_pf + mean_fg + mean_ts
## 
##             Df Deviance    AIC
## - mean_G     1   1.9614 32.404
## - mean_ws    1   1.9668 32.489
## - mean_trb   1   1.9710 32.555
## - mean_ts    1   1.9751 32.619
## - mean_vorp  1   1.9944 32.921
## - mean_tov   1   1.9969 32.961
## - mean_fg    1   2.0151 33.242
## - mean_ast   1   2.0229 33.360
## - mean_per   1   2.0513 33.793
## &lt;none&gt;           1.9611 34.399
## - mean_pf    1   2.0938 34.429
## - mean_stl   1   2.1172 34.773
## - mean_age   1   2.1226 34.852
## - mean_3p    1   2.2228 36.283
## - mean_blk   1   2.2418 36.547
## 
## Step:  AIC=32.4
## playoff ~ mean_per + mean_trb + mean_ast + mean_blk + mean_3p + 
##     mean_age + mean_stl + mean_tov + mean_vorp + mean_ws + mean_pf + 
##     mean_fg + mean_ts
## 
##             Df Deviance    AIC
## - mean_ws    1   1.9670 30.492
## - mean_trb   1   1.9718 30.567
## - mean_ts    1   1.9769 30.649
## - mean_vorp  1   1.9961 30.947
## - mean_tov   1   2.0003 31.013
## - mean_ast   1   2.0311 31.486
## - mean_fg    1   2.0320 31.500
## - mean_per   1   2.0527 31.815
## &lt;none&gt;           1.9614 32.404
## - mean_pf    1   2.0943 32.436
## - mean_age   1   2.1304 32.966
## - mean_stl   1   2.1314 32.981
## - mean_3p    1   2.2233 34.289
## - mean_blk   1   2.2507 34.669
## 
## Step:  AIC=30.49
## playoff ~ mean_per + mean_trb + mean_ast + mean_blk + mean_3p + 
##     mean_age + mean_stl + mean_tov + mean_vorp + mean_pf + mean_fg + 
##     mean_ts
## 
##             Df Deviance    AIC
## - mean_trb   1   1.9782 28.668
## - mean_ts    1   1.9833 28.748
## - mean_tov   1   2.0004 29.014
## - mean_ast   1   2.0311 29.487
## - mean_fg    1   2.0339 29.530
## - mean_per   1   2.0530 29.818
## &lt;none&gt;           1.9670 30.492
## - mean_pf    1   2.1070 30.624
## - mean_stl   1   2.1343 31.023
## - mean_age   1   2.1566 31.345
## - mean_blk   1   2.2516 32.681
## - mean_3p    1   2.3205 33.615
## - mean_vorp  1   3.6798 47.909
## 
## Step:  AIC=28.67
## playoff ~ mean_per + mean_ast + mean_blk + mean_3p + mean_age + 
##     mean_stl + mean_tov + mean_vorp + mean_pf + mean_fg + mean_ts
## 
##             Df Deviance    AIC
## - mean_tov   1   2.0004 27.014
## - mean_ts    1   2.0071 27.118
## - mean_fg    1   2.0526 27.813
## - mean_ast   1   2.0643 27.989
## &lt;none&gt;           1.9782 28.668
## - mean_per   1   2.1108 28.680
## - mean_pf    1   2.1469 29.206
## - mean_age   1   2.1671 29.495
## - mean_stl   1   2.1696 29.531
## - mean_blk   1   2.3055 31.415
## - mean_3p    1   2.4235 32.962
## - mean_vorp  1   3.8036 46.935
## 
## Step:  AIC=27.01
## playoff ~ mean_per + mean_ast + mean_blk + mean_3p + mean_age + 
##     mean_stl + mean_vorp + mean_pf + mean_fg + mean_ts
## 
##             Df Deviance    AIC
## - mean_ts    1   2.0338 25.528
## - mean_fg    1   2.0901 26.373
## - mean_ast   1   2.0929 26.415
## - mean_per   1   2.1276 26.926
## &lt;none&gt;           2.0004 27.014
## - mean_pf    1   2.1481 27.223
## - mean_stl   1   2.1704 27.543
## - mean_age   1   2.2012 27.979
## - mean_blk   1   2.3958 30.606
## - mean_3p    1   2.6472 33.700
## - mean_vorp  1   4.1079 47.321
## 
## Step:  AIC=25.53
## playoff ~ mean_per + mean_ast + mean_blk + mean_3p + mean_age + 
##     mean_stl + mean_vorp + mean_pf + mean_fg
## 
##             Df Deviance    AIC
## - mean_fg    1   2.1067 24.619
## - mean_per   1   2.1287 24.941
## - mean_ast   1   2.1485 25.229
## - mean_pf    1   2.1572 25.354
## &lt;none&gt;           2.0338 25.528
## - mean_stl   1   2.1909 25.835
## - mean_age   1   2.2226 26.279
## - mean_blk   1   2.3959 28.607
## - mean_3p    1   2.6965 32.271
## - mean_vorp  1   4.2409 46.309
## 
## Step:  AIC=24.62
## playoff ~ mean_per + mean_ast + mean_blk + mean_3p + mean_age + 
##     mean_stl + mean_vorp + mean_pf
## 
##             Df Deviance    AIC
## - mean_pf    1   2.1579 23.364
## - mean_per   1   2.1933 23.868
## &lt;none&gt;           2.1067 24.619
## - mean_age   1   2.2940 25.260
## - mean_stl   1   2.3123 25.506
## - mean_ast   1   2.4910 27.814
## - mean_blk   1   2.5157 28.119
## - mean_3p    1   2.7085 30.409
## - mean_vorp  1   4.3125 44.827
## 
## Step:  AIC=23.36
## playoff ~ mean_per + mean_ast + mean_blk + mean_3p + mean_age + 
##     mean_stl + mean_vorp
## 
##             Df Deviance    AIC
## - mean_per   1   2.2469 22.617
## &lt;none&gt;           2.1579 23.364
## - mean_age   1   2.3429 23.914
## - mean_stl   1   2.4006 24.668
## - mean_ast   1   2.4932 25.841
## - mean_blk   1   2.5291 26.284
## - mean_3p    1   2.7794 29.210
## - mean_vorp  1   4.4490 43.793
## 
## Step:  AIC=22.62
## playoff ~ mean_ast + mean_blk + mean_3p + mean_age + mean_stl + 
##     mean_vorp
## 
##             Df Deviance    AIC
## &lt;none&gt;           2.2469 22.617
## - mean_age   1   2.4424 23.203
## - mean_stl   1   2.4711 23.566
## - mean_ast   1   2.5019 23.950
## - mean_blk   1   2.8611 28.108
## - mean_3p    1   3.0357 29.945
## - mean_vorp  1   4.7114 43.570</code></pre>
<pre><code>## 
## Call:
## glm(formula = playoff ~ mean_age + mean_stl + mean_ast + mean_blk + 
##     mean_3p, family = &quot;binomial&quot;, data = combine6)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4034  -0.7746  -0.0805   0.5740   2.7159  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -48.75805   19.25080  -2.533   0.0113 *
## mean_age      1.35176    0.61207   2.208   0.0272 *
## mean_stl      0.36524    0.19514   1.872   0.0612 .
## mean_ast     -0.06588    0.07378  -0.893   0.3719  
## mean_blk     -0.16573    0.16749  -0.990   0.3224  
## mean_3p      34.87594   16.65645   2.094   0.0363 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 42.943  on 30  degrees of freedom
## Residual deviance: 27.416  on 25  degrees of freedom
## AIC: 39.416
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" />
For 2016’s data, we showed our AIC steps for better visualization of how we end up with our best predictors. Our AIC value dropped to 22.62 with predictor variables: age, steal, assist,block, three point and Value over Replacement Player. Our logistic regression has shown multiple significant predictors and a strong ROC-AUC Curve model with the AUC value of 0.896. So we believed this will be the best candidate model for us to make the final prediction.</p>
<p>Here is the <a href="/analysis2/">second analysis page</a>.</p>
</div>
