---
title: blog Post 3
author: GWXYZ
date: '2022-10-28'
slug: []
categories: []
tags: []
description: data cleaning and intial exploration of data
toc: yes
authors: []
series: []
lastmod: '2022-10-28T22:16:52-04:00'
featuredVideo: ~
featuredImage: ~
---


<div id="TOC">

</div>

<div id="data-choice" class="section level2">
<h2>Data choice</h2>
<p>We decide to use our data set 2, which is College completion data from 3,800 degree-granting institutions in the US. <a href="https://data.world/databeats/college-completion" class="uri">https://data.world/databeats/college-completion</a></p>
</div>
<div id="data-cleaning" class="section level2">
<h2>Data cleaning</h2>
<p>we first cleaned the data by removing variables that has too many missing value and has no contribution to our data analysis. then we replace every missing value which has the letter “NULL” to blank value na, which helps us to better process the data.</p>
<pre class="r"><code>library(readr)
library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
## ✔ ggplot2 3.3.6      ✔ dplyr   1.0.10
## ✔ tibble  3.1.8      ✔ stringr 1.4.1 
## ✔ tidyr   1.2.0      ✔ forcats 0.5.2 
## ✔ purrr   0.3.4      
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>cc &lt;- read.csv(&quot;/Users/ziv/Documents/ma 415 project/ma4615-fa22-final-project-gwxyz/dataset/cc_institution_details.csv&quot;)
cc_clean&lt;- select(cc, -(basic:site), -(vsa_year:cohort_size), -(med_sat_value:med_sat_percentile))%&gt;%
  mutate(across(everything(), ~replace(., . ==  &quot;NULL&quot; , NA)))</code></pre>
</div>
<div id="data-exploration" class="section level2">
<h2>Data exploration</h2>
<pre class="r"><code>c1&lt;- filter(cc_clean, awards_per_value &lt;100)
ggplot(c1) +
  geom_point(mapping = aes(x = exp_award_state_value, y=awards_per_value, color = control))+
  geom_smooth(mapping = aes(x = exp_award_state_value, y=awards_per_value))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>summary(cc_clean$exp_award_state_value)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   12346   35830   54025   61282   79310  188870</code></pre>
<pre class="r"><code>c1%&gt;% group_by(control)%&gt;%
  summarize(mean_spending = mean(exp_award_state_value, na.rm = TRUE),
            count = n())</code></pre>
<pre><code>## # A tibble: 3 × 3
##   control                mean_spending count
##   &lt;chr&gt;                          &lt;dbl&gt; &lt;int&gt;
## 1 Private for-profit            36624.   990
## 2 Private not-for-profit        94276.  1247
## 3 Public                        50575.  1558</code></pre>
</div>
<div id="section" class="section level2">
<h2></h2>
<p>A trend that we see in this chart is that it seems students with less college spending has a higher percentage of college completion. we also did a summary stats on the mean spending by different institute type. Private not-for-profit college has the highest spending and public school has the least spending. the mean student spending across all college in the data set is $61282</p>
<pre class="r"><code>new_england &lt;- filter(cc_clean, state %in% c(&quot;Massachusetts&quot;,&quot;Connecticut&quot;, &quot;Maine&quot;, &quot;New Hampshire&quot;, &quot;New Jersey&quot;,&quot;New York&quot; ))
ggplot(new_england) + geom_bar(aes(x = state, fill = control), position = &quot;fill&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>ggplot(cc_clean) + geom_bar(aes(x = state, fill = control), position = &quot;fill&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code>new_england%&gt;%
  group_by(state) %&gt;%
  summarize(mean_student = mean(student_count, na.rm = TRUE),
            count = n())</code></pre>
<pre><code>## # A tibble: 6 × 3
##   state         mean_student count
##   &lt;chr&gt;                &lt;dbl&gt; &lt;int&gt;
## 1 Connecticut          4566.    35
## 2 Maine                2137.    29
## 3 Massachusetts        3741.   100
## 4 New Hampshire        3026.    24
## 5 New Jersey           6313.    55
## 6 New York             4235.   241</code></pre>
<pre class="r"><code>new_england%&gt;%
  group_by(state) %&gt;%
  summarize(mean_completion = mean(awards_per_value),
            count = n())</code></pre>
<pre><code>## # A tibble: 6 × 3
##   state         mean_completion count
##   &lt;chr&gt;                   &lt;dbl&gt; &lt;int&gt;
## 1 Connecticut              19.7    35
## 2 Maine                    23.6    29
## 3 Massachusetts            23.2   100
## 4 New Hampshire            23.7    24
## 5 New Jersey               19.9    55
## 6 New York                 23.5   241</code></pre>
<pre class="r"><code>country &lt;- cc_clean%&gt;%
  group_by(state) %&gt;%
  summarize(mean_completion = mean(awards_per_value),
            count = n())
ggplot(country) + stat_summary(
  aes(x = state, y = mean_completion), geom = &quot;bar&quot;, fill = &quot;orange&quot;)</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-3.png" width="672" /></p>
<pre class="r"><code>summary(cc_clean$awards_per_value)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.50   17.30   21.30   23.44   26.50  137.60</code></pre>
</div>
<div id="section-1" class="section level1">
<h1></h1>
<p>We explored school’s completion rate from US and the school in the New England area, which is consistently pretty low with mean value of 23.44% completion</p>
</div>
