---
title: "Blog Post 5"
author: "GWXYZ"
date: '2022-11-12'
slug: []
categories: []
tags: []
description: Research topic and combined data
toc: yes
authors: []
series: []
lastmod: '2022-11-12T21:57:22-05:00'
featuredVideo: ~
featuredImage: ~
---

## Combining Data
The dataset we are combining with injury data of season 2014-2015, 2015-2016, 2016-2017 in order to predict the final result of 2017-2018 season. We use the injury data in order to get a better understanding of the team line-up in every play and also the effect of injuries on the chance of winning. We also combine with the salary cap in order to understand the relationship between the wealth of a team and its chance of winning.

In order to combine the datasets, we need to further clean our original datasets. To combine the injury data with our original data, we have to change the data of injury time period into year, and combine the datasets by year and player name. Then we need to clean the data by grouping them by team for every year and find the average data for every team, so we can combine the playoffs data with it. Finally, we can filter the data from the three seasons 2014-2015, 2015-2016, 2016-2017 and do further research. 

## Cleaning Data

```{r}
library(tidyverse)
library(rvest)

nba_clean <- read_csv("/Users/xuduoyifu/Desktop/大四/MA415/HW/ma4615-fa22-final-project-gwxyz/dataset/nba_clean.csv")

playoffs <- nba_clean%>%
  filter(SeasonStart%in%c("2014","2015","2016"))%>%
  filter(Tm%in%c("IND","MIA", "TOT", "CHA", "WAS", "BRK","CHI", "ATL","SAS","OKC","LAC","HOU","POR","GSW","MEM","DAL",
                 "NOP", "CLE", "TOR", "BOS", "MIL",
                 "DET"))

Injury <- read_csv("/Users/xuduoyifu/Desktop/大四/MA415/HW/ma4615-fa22-final-project-gwxyz/dataset/injuries_2010-2020 2.csv", col_types = cols_only(Date = col_character(), Team = col_character(), Relinquished = col_character()))

colnames(Injury)[3] <- "PlayerName"
colnames(Injury)[1] <- "SeasonStart"
colnames(Injury)[2] <- "Tm"
Injury <- Injury %>% filter(!is.na(PlayerName))
Injury <- Injury %>% mutate(injuries_data = 1)
Injury$SeasonStart <- substr(Injury$SeasonStart,1,4)
Injury_clean <- Injury %>% filter(SeasonStart %in% c("2014","2015","2016"))
playoffs <- nba_clean%>%
  filter(SeasonStart%in%c("2014","2015","2016"))%>%
  filter(Tm%in%c("IND","MIA", "TOT", "CHA", "WAS", "BRK","CHI", "ATL","SAS","OKC","LAC","HOU","POR","GSW","MEM","DAL",
                 "NOP", "CLE", "TOR", "BOS", "MIL",
                 "DET"))
playoffs$SeasonStart <- as.character(playoffs$SeasonStart)
Injury_clean<- Injury_clean %>%
  mutate(Tm = recode(Tm, 'Pacers' = 'IND', 'Heat' = 'MIA','Hornets' = 'CHA','Wizards' = 'WAS','Nets' = 'BRK',
                       'Bulls' = 'CHI','Hawks' = 'ATL','Spurs' = 'SAS','Thunder' = 'OKC', 'Thunder' = 'LAC','Rockets' = 'HOU',
                       'Blazers' = 'POR','Warriors' = 'GSW','Grizzlies' = 'MEM','Mavericks' = 'DAL','Pelicans' = 'NOP','Cavaliers' = 'CLE',
                       'Raptors' = 'TOR','Celtics' = 'BOS','Bucks' = 'MIL','Pistons' = 'DET'))%>%
  filter(Tm%in%c("IND","MIA", "TOT", "CHA", "WAS", "BRK","CHI", "ATL","SAS","OKC","LAC","HOU","POR","GSW","MEM","DAL",
                   "NOP", "CLE", "TOR", "BOS", "MIL",
                   "DET"))

combine <- playoffs %>% left_join(Injury_clean, by = c("PlayerName","SeasonStart","Tm"))
```
